{{- if .Values.service.vegagatewaypro.ingress.enabled -}}
{{ if .Values.service.vegagatewaypro.ingress.interface }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.moduleName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500M"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: Accept-Language,Authorization,Content-Type,Host,Jwt-Token,Kbn-Xsrf,Language,Origin,Token,User,User-Agent,Userid,X-Http-Method-Override,X-Language
    nginx.ingress.kubernetes.io/cors-allow-methods: GET,PUT,POST,DELETE,OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
{{- if index .Values.depServices "class-443" "ingressClass" }}
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
{{- end }}
  rules:
  - http:
      paths:
        {{- range .Values.service.vegagatewaypro.ingress.interface.path }}
        - path: {{ . }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $.Values.moduleName }}-svc
              port:
                number: {{ $.Values.service.vegagatewaypro.port }}
        {{- end }}
{{ end }}
{{- end }}
