apiVersion: v1
kind: Service
metadata:
  name: workflow-manage-client
  namespace: {{ .Values.namespace }}
  labels:
    app: workflow-manage-client
spec:
{{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  ports:
    - name: public-port
      port: 1104
      protocol: TCP           
  selector:
    app: workflow-manage-client
  type: {{ .Values.service.type }}