replicaCount: 1

namespace: dip
moduleName: doc-audit-client

image:
  registry: acr.aishu.cn
  repository: /dip/doc-audit-client
  tag: 3.0.0.5
  pullPolicy: IfNotPresent
  name: doc-audit-client

service:
  # ingressclassname: ''
  # agentWEB:
  #   type: ClusterIP
  #   port: 1105
  #   nodePort: 1105
  #   ingress:
  #     enabled: true
  #     interface:
  #       path:
  #         - /doc-audit-client
  # enableDualStack: false
  type: ClusterIP
  # ports:
  #   port1: 1105
  #   protocol1: TCP
  #   targetPort1: 1105
  #   name1: doc-audit-client
  enableSensitiveWordDetection: false

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 11
    memory: 20Gi

probe:
  livenessProbe:
    httpGet:
      path: /probe
      port: 1105
    initialDelaySeconds: 25
    periodSeconds: 50
    timeoutSeconds: 20
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /probe
      port: 1105
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /probe
      port: 1105
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

nodeSelector: {}

depServices:

enableSystemLog: true

rps:
  limit: 100 #每秒最大请求数
