replicaCount: 1

nodeSelector: {}

namespace: anyshare

image:
  registry: registry.aishu.cn:15000
  repository: /
  tag: 7.0.1
  pullPolicy: IfNotPresent
  workflowconfig:
    repository: /
    wctag: 7.0.1

env:
  timezone: Asia/Shanghai
  language: zh_CN.UTF-8

service:
  type: ClusterIP
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  startupProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  language: zh_CN
  enableDualStack: false
  moduleVersion: 7.0.5.5
depServices:
  redis:
    connectType: sentinel
    connectInfo:
      masterGroupName: mymaster
      password: eisoo.com123
      sentinelHost: proton-redis-proton-redis-sentinel.resource
      sentinelPassword: eisoo.com123
      sentinelPort: 26379
      sentinelUsername: root
      username: root
    enableSSL: false
    secretName: redis-ssl-secret
    caName: ca.pem
    certName: cert.pem
    keyName: key.pem
  rds:
    system_id: ""
    host: mariadb-mariadb-master.resource
    port: 3330
    database: "adp"
    user: "anyshare"
    password: "eisoo.com123"
    type: "mysql"
  mq:
    auth: null
    mqHost: proton-mq-nsq-nsqd.resource
    mqLookupdHost: proton-mq-nsq-nsqlookupd.resource
    mqLookupdPort: 4161
    mqPort: 4151
    mqType: nsq
  nsq:
    nsqlookupdHost: proton-mq-nsq-nsqlookupd.resource
    nsqlookupdPort: 4161
    nsqdHost: proton-mq-nsq-nsqd.resource
    nsqdPort: 4150
  user-management:
    privateHost: user-management-private
    privatePort: 30980
  efast:
    evfsThriftHost: efast-evfs
    evfsThriftPort: 9064
    privateHttpHost: efast-private
    privateHttpPort: 9123
  eacp:
    privateHttpHost: eacp-private
    privateHttpPort: 9998
    thriftHost: eacp-thrift
    thriftPort: 9992
  doc-share:
    publicHost: doc-share-public
    publicPort: 30920
    privateHost: doc-share-private
    privatePort: 30920
  hydra:
    administrativeHost: hydra-admin
    administrativePort: 4445
    administrativePrefix: "/admin"
  docset:
    privateHost: docset-private
    privatePort: 32597
  log:
    host: log
    port: 9993
  sharemgnt:
    host: sharemgnt
    port: 9600
  deploy-service:
    HttpHost: deploy-service
    HttpPort: 9703
  document:
    privateHost: document-private
    privatePort: 30920
  appstore-public:
    host: appstore-public
    port: 7010
  personal-config-private:
    privateHost: personal-config-private
    privatePort: 8082
  message:
    privateHost: message-private
    privatePort: 30935
  kc:
    privateHost: kc-mc-private
    privatePort: 7203

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 4
    memory: 8192Mi

securityContext:
  runAsGroup: 5000
  runAsUser: 5000
  readOnlyRootFilesystem: true